config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :reviews

  root 'welcome#index'

  get 'rankings' => 'rankings#index'
  get 'rankings/green' => 'rankings#green'
  get 'rankings/blue' => 'rankings#blue'
  get 'rankings/red' => 'rankings#red'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/review.rb
class Review < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord

	before_save {self.email = email.downcase}
	validates(:name, presence: true)
	validates(:email, presence: true)
	validates :name,  presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  	validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  	validates :password, presence: true, length: { minimum: 6 }
  	
  	has_secure_password
end

app/models/vendor.rb
class Vendor < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/rankings_controller.rb
class RankingsController < ApplicationController

	def index
		@vendors = Vendor.order(rating: :desc)
	end

	def green
		@green_reviews = Review.where(:vendor => 'green')
	end

	def red
		@red_reviews = Review.where(:vendor => 'red')
	end

	def blue
		@blue_reviews = Review.where(:vendor => 'blue')
	end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

	def index
    	@reviews = Review.all
  	end
	
	def show
		@review = Review.find(params[:id])
	end

	def new
	end

	def create
		@review = Review.new(review_params)
		@review.save

		vendor_name = params[:review][:vendor]
		vendor = Vendor.find_by(name: vendor_name)
		rating = params[:review][:rating].to_f
		if vendor
			num_reviews = vendor[:num_reviews] +1
			new_rating = (1.0/num_reviews*rating) + ((num_reviews-1)*vendor[:rating]/num_reviews)
			vendor.num_reviews = num_reviews
			vendor.rating = new_rating
		else
			#enter vendor info into database
			vendor = Vendor.new(:name => vendor_name, :num_reviews => 1, :rating => rating)
		end
		vendor.save

		redirect_to @review
	end

	private
		def review_params
			params.require(:review).permit(:vendor, :rating, :experiences, :improvements)
		end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mobius</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rankings/blue.html.erb
<h2 style = "color: blue;">Blue Transportation Reviews</h2>
<br>

<table class = "table">
	<thead>
		<tr>
			<th>Rating</th>
			<th>Review</th>
		</tr>
	</thead>
	<tbody>
	<% @blue_reviews.find_each(batch_size: 5000) do |review| %>
		<tr>
			<td><%= review.rating %></td>
			<td><%= review.experiences %></td>
		</tr>
	<% end %>

	</tbody>
</table>

app/views/rankings/green.html.erb
<h2 style = "color: green;">Green Transportation Reviews</h2>
<br>

<table class = "table">
	<thead>
		<tr>
			<th>Rating</th>
			<th>Review</th>
		</tr>
	</thead>
	<tbody>
	<% @green_reviews.find_each(batch_size: 5000) do |review| %>
		<tr>
			<td><%= review.rating %></td>
			<td><%= review.experiences %></td>
		</tr>
	<% end %>

	</tbody>
</table>

app/views/rankings/index.html.erb
<h1>PT-1 Vendors Listed by Overall Rank</h1>

<br><br>
<% @vendors.each do |vendor| %>
	<h2><%= link_to vendor.name%></h2>
	<h4><%= vendor.rating %></h4>
<% end %>

<!--
=begin
<h2> <%= link_to 'Green Transportation', rankings_green_path, {style: "color: green"} %></h2>
<p>Rating: 4.2</p>

<h2> <%= link_to 'Red Transportation', rankings_red_path, {style: "color: red"}%></h2>
<p>Rating: 3.9</p>

<h2> <%= link_to 'Blue Transportation', rankings_blue_path, {style: "color: blue"}%></h2>
<p>Rating: 3.5</p>
=end
-->

app/views/rankings/red.html.erb
<h2 style = "color: red;">Red Transportation Reviews</h2>
<br>

<table class = "table">
	<thead>
		<tr>
			<th>Rating</th>
			<th>Review</th>
		</tr>
	</thead>
	<tbody>
	<% @red_reviews.find_each(batch_size: 5000) do |review| %>
		<tr>
			<td><%= review.rating %></td>
			<td><%= review.experiences %></td>
		</tr>
	<% end %>

	</tbody>
</table>

app/views/reviews/index.html.erb
<h1>All PT-1 Reviews</h1>

<table class = "table">
  <thead>
    <tr>
      <th>Vendor</th>
      <th>Rating</th>
    </tr>
  </thead>

  <tbody>
  <% @reviews.find_each(batch_size: 5000) do |review|%>
    <tr>
      <td><%= review.vendor %></td>
      <td><%= review.rating %></td>
      <td><%= link_to 'Show This Review', review_path(review) %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/reviews/new.html.erb
<h1> New Review </h1>

<%= form_for :review, url: reviews_path do |f| %>

  <h4>Which PT-1 vendor did you use?</h4>
  <p>
    <%= f.radio_button :vendor, "blue" %>
    <%= label :vendor_blue, "Blue Transportation" %>
    <%= f.radio_button :vendor, "red" %>
    <%= label :vendor_red, "Red Transportation" %>
    <%= f.radio_button :vendor, "green" %>
    <%= label :vendor_green, "Green Transportation" %>
  </p>

  <h4>How satisfied were you with this vendor?</h4>
  <p>
    <%= f.radio_button :rating, 5 %>
    <%= label_tag :rating_5, "Very Satisfied" %>
    <%= f.radio_button :rating, 4 %>
    <%= label_tag :rating_4, "Satisfied" %>
    <%= f.radio_button :rating, 3 %>
    <%= label_tag :rating_3, "No Opinion" %>
    <%= f.radio_button :rating, 2 %>
    <%= label_tag :rating_2, "Dissatisfied" %>
    <%= f.radio_button :rating, 1 %>
    <%= label_tag :rating_1, "Very Dissatisfied" %>
  </p>

  <h4>Briefly describe your experiences with this vendor.</h4>
  <p>
    <%= f.text_area :experiences %>
  </p>

  <h4>How can your PT-1 improve its service?</h4>
  <p>
    <%= f.text_area :improvements %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/reviews/show.html.erb
<h2> Here is your review! </h2>

<p>
  <strong>Vendor:</strong>
  <%= @review.vendor %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @review.rating %>
</p>

<p>
  <strong>Experiences:</strong>
  <%= @review.experiences %>
</p>

<p>
  <strong>Improvements:</strong>
  <%= @review.improvements %>
</p>

<%= link_to 'Go to Homepage', root_path, {class: "btn btn-success"} %>

app/views/welcome/index.html.erb
<h1>Mobius</h1>

<ul class="nav nav-pills">
  <li role="presentation" class="active">
    <%= link_to 'Home', root_path%>
  </li>

  <li role="presentation", class = "dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">PT-1 Reviews <span class="caret"></span></a>

    <ul class="dropdown-menu">
      <li><%= link_to 'Rate a Vendor', new_review_path%></li>
      <li class="divider"></li>
      <li><%= link_to 'View Reviews', reviews_path%></li>
      <li class="divider"></li>
      <li><%= link_to 'Vendor Rankings', rankings_path%></li>
    </ul>
  </li>

  </li>
  <li role="presentation">
    <%= link_to 'Forum', root_path%>
  </li>
  <li role="presentation">
    <%= link_to 'Calendar', root_path%>
  </li>
</ul>

<br><br>

<p> Stunning display and info about our services</p>